
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
    public class tblAddress : _tblAddress
    {
        public tblAddress()
        {

        }
        public DataTable loadAllAdress(string strCustomerID = "",bool strIsdefault =false)
        {

            string StrQuery = "select  tblAddress.* ,appFirstName+' '+appLastName as appName,tblCountry.appCountry,tblCity.appCity,tblState.appState from tblAddress ";
            StrQuery += " inner join tblCustomer on tblCustomer.appCustomerID=tblAddress.appCustomerID ";
            StrQuery += " inner join tblCity on tblCity.appCityId=tblAddress.appCityId ";
            StrQuery += " inner join tblState on tblAddress.appStateId=tblState.appStateId ";
            StrQuery += " inner join tblCountry on tblCountry.appCountryId=tblAddress.appCountryId ";

            if (strCustomerID != "")
            {
                StrQuery += "where tblAddress.appCustomerID=" + strCustomerID;
            }
            if (strIsdefault == true)
            {
                StrQuery += "and tblAddress.appIsDefault=1";
            }
            StrQuery += " order by tblAddress.appAddressId ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public void setDefault(string strCustomerID = "",string strAdressID ="")
        {

            string StrQuery = "update tblAddress set appIsDefault=0  ";
          
            if (strCustomerID != "")
            {
                StrQuery += "where tblAddress.appCustomerID=" + strCustomerID;
            }
            if (strAdressID != "")
            {
                StrQuery += "and tblAddress.appAddressId!=" + strAdressID;
            }
         
            base.LoadFromRawSql(StrQuery);
            string StrQuery1 = "update tblAddress set appIsDefault=1  ";

            if (strCustomerID != "")
            {
                StrQuery1 += "where tblAddress.appCustomerID=" + strCustomerID;
            }
            if (strAdressID != "")
            {
                StrQuery1 += "and tblAddress.appAddressId=" + strAdressID;
            }

            base.LoadFromRawSql(StrQuery1);
        }
    }
}
