
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
	public class tblBanner : _tblBanner
	{
		public tblBanner()
		{
		
		}
        public DataTable LoadGridData(string strColumnName, string strColumnValue)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = "select appBannerID, appTitle, appImage,appIsActive,appDisplayOrder from tblBanner ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += "where " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            StrQuery += " order by appDisplayOrder ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadBanner()
        {

            string StrQuery = "select appBannerID, appTitle, appImage,appIsActive,appDisplayOrder,appUrl,appDescription from tblBanner Where appIsActive=1 order by appDisplayOrder ";

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
	}
}
