
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
    public class tblBestSeller : _tblBestSeller
    {
        public tblBestSeller()
        {

        }

        public DataTable LoadGridData(string strColumnName, string strColumnValue)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = "select tblBestSeller.appBestSellerID,tblBestSeller.appProductID,tblBestSeller.appIsActive,tblBestSeller.appDisplayOrder,tblProduct.appProductName,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblProductImage.appThumbImage,tblProductImage.appNormalImage,tblProductDetail.appPrice,tblProduct.appIsFeatured,tblProduct.appIsNewArrival,tblProduct.appIsBestSeller ";
            StrQuery += " from tblBestSeller";
            StrQuery += " inner join tblProduct on tblProduct.appProductID=tblBestSeller.appProductID ";
            StrQuery += " inner join tblProductColor on tblProductColor.appProductID=tblProduct.appProductID ";
            StrQuery += " inner join tblColor on tblColor.appColorID=tblProductColor.appColorID ";
            StrQuery += " inner join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID ";
            StrQuery += "  inner join tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID ";
            StrQuery += " Where  tblProduct.appIsActive=1 and tblProductColor.appIsDefault=1 and tblProductImage.appIsDefault=1 and tblProductDetail.appIsDefault=1       ";


            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += "and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            StrQuery += " order by tblBestSeller.appDisplayOrder ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadBestSeller(string strTopRecord = "")
        {
            string StrQuery = "Select ";
            if (strTopRecord != "")
            {
                StrQuery += " Top " + strTopRecord;
            }

            StrQuery += "   tblProductDetail.appMRP, tblBestSeller.appBestSellerID,tblBestSeller.appProductID,tblBestSeller.appIsActive,tblBestSeller.appDisplayOrder,tblProduct.appProductName,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblProductImage.appSmallImage,tblProductImage.appNormalImage,tblProductImage.appLargeImage,tblProduct.appIsFeatured,tblProduct.appIsNewArrival,tblProduct.appIsBestSeller,tblProductDetail.appProductDetailID,case when tblDeal.appDiscountPer is null then cast(ROUND(dbo.tblProductDetail.appPrice,0) as int) else cast(ROUND((isnull(tblProductDetail.appPrice,0)-((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100)),0) as int) end  appPrice, cast(ROUND(tblProductDetail.appMRP,0) as int) appMRP  ,  case when tblDeal.appDiscountPer is null then Cast(ROUND((100-(isnull(dbo.tblProductDetail.appPrice,0)*100)/isnull(dbo.tblProductDetail.appMRP,0)),0) as int) else Cast(ROUND((100-(isnull( cast((isnull(tblProductDetail.appPrice,0)-((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100)) as Decimal(10,2)),0)*100)/isnull(dbo.tblProductDetail.appMRP,0)),0) as int) end appOff  ";
            StrQuery += "    from tblBestSeller inner join tblProduct on tblProduct.appProductID=tblBestSeller.appProductID and tblBestSeller.appIsActive=1 ";
            StrQuery += "     inner join tblProductColor on tblProductColor.appProductID=tblProduct.appProductID and tblProductColor.appIsDefault=1 ";
            StrQuery += "    inner join tblColor on tblColor.appColorID=tblProductColor.appColorID ";
            StrQuery += "   inner join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID and tblProductImage.appIsDefault=1  ";
            StrQuery += "    inner join tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID and tblProductDetail.appIsDefault=1 ";
            StrQuery += "    Left Join tblDeal on tblDeal.appProductID=tblProduct.appProductID ";
            StrQuery += " Where  tblProduct.appIsActive=1 order by appDisplayOrder ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;

        }

        public DataTable LoadBestSelllerList(string strCategoryId, string strSubCategoryId, string strColorId)
        {
            string StrQuery = "Select vw_SerachProduct.* From vw_SerachProduct ";
            StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Where 1=1 ";
            if (strCategoryId != "" && strCategoryId != "0")
            {
                StrQuery += " And tblSubCategory.appCategoryID=" + strCategoryId;
            }
            if (strSubCategoryId != "" && strSubCategoryId != "0")
            {
                StrQuery += " And tblSubCategory.appSubCategoryID=" + strSubCategoryId;
            }
            StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=vw_SerachProduct.appProductID ";

            StrQuery += " Where 1=1 ";

            if (strColorId != "" && strColorId != "0")
            {
                StrQuery += " And appColorId =" + strColorId;
            }
            else
            {
                StrQuery += " And appProductColorIsDefault=1";
            }
            StrQuery += " And appProductDetailIsDefault=1";
            StrQuery += " and vw_SerachProduct.appProductID not in ( Select tblBestSeller.appProductID From tblBestSeller)";
            StrQuery += " Order by vw_SerachProduct.appProductID Desc";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadAllProductByPaging(string strPageSize, string strPageIndex, string strProperty, string strColor, string strSize, string strOrderBy, string strMinPrice, string strMaxPrice, string strRate)
        {

            string StrQuery = "Select * From ( Select ROW_NUMBER() OVER( ORDER BY ";
            if (strOrderBy != "")
            {
                StrQuery += strOrderBy;
            }
            //else
            //{
            //    StrQuery += " vw_SerachProduct.appProductID Desc";
            //}

            StrQuery += " )AS RowNumber,CASE WHEN tblDeal.appDiscountPer IS NULL THEN tblProductDetail.appPrice ELSE CAST((isnull(tblProductDetail.appPrice, 0) - ((isnull(tblProductDetail.appPrice, 0) * tblDeal.appDiscountPer) / 100)) AS Decimal(10, 2)) END AS AppPrice,tblProductColor.appProductColorID,tblProductDetail.AppSizeID, tblProductDetail.AppMRP,tblBestSeller.appBestSellerID,tblBestSeller.appProductID,tblBestSeller.appIsActive,tblBestSeller.appDisplayOrder,tblProduct.appProductName,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblProductImage.appSmallImage,tblProductImage.appNormalImage,tblProductImage.appLargeImage,tblProduct.appIsFeatured,tblProduct.appIsNewArrival,tblProduct.appIsBestSeller,tblProductDetail.appProductDetailID ,case when tblDeal.appDiscountPer is null then Cast(ROUND((100-(isnull(dbo.tblProductDetail.appPrice,0)*100)/isnull(dbo.tblProductDetail.appMRP,0)),0) as Decimal(2)) else Cast(ROUND((100-(isnull( cast((isnull(tblProductDetail.appPrice,0)-((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100)) as Decimal(10,2)),0)*100)/isnull(dbo.tblProductDetail.appMRP,0)),0) as decimal(2,0))  end appOff  ";
            StrQuery += "    from tblBestSeller inner join tblProduct on tblProduct.appProductID=tblBestSeller.appProductID and tblBestSeller.appIsActive=1 ";
            StrQuery += "     inner join tblProductColor on tblProductColor.appProductID=tblProduct.appProductID   ";
            if (strColor == "")
            {
                StrQuery += "  and tblProductColor.appIsDefault=1 ";
            }
            StrQuery += "    inner join tblColor on tblColor.appColorID=tblProductColor.appColorID ";
            StrQuery += "   inner join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID and tblProductImage.appIsDefault=1  ";
            StrQuery += "    inner join tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID and tblProductDetail.appIsDefault=1 ";
            StrQuery += " Left Join tblDeal on tblDeal.appProductID=tblProduct.appProductID ";
            if (strProperty != "")
            {
                StrQuery += " INNER JOIN (Select appProductID From tblProductProperty Where tblProductProperty.appPropertyPreValueID in (" + strProperty + ") group by appProductID) tblProductProperty On tblProductProperty.appProductId=tblBestSeller.appProductId";
            }
            StrQuery += " Where 1=1 ";

            if (strColor != "")
            {
                StrQuery += " And tblProductColor.appColorId In(" + strColor + ")";
            }
            else
            {
                StrQuery += " And tblProductColor.appIsDefault=1";
            }
            if (strMinPrice != "" && strMaxPrice != "")
            {
                StrQuery += " and ((CASE WHEN tblDeal.appDiscountPer IS NULL THEN tblProductDetail.appPrice ELSE CAST((isnull(tblProductDetail.appPrice, 0) - ((isnull(tblProductDetail.appPrice, 0) * tblDeal.appDiscountPer) / 100)) AS Decimal(10, 2)) END)*" + strRate + ") between " + strMinPrice + " and " + strMaxPrice + "";
            }
            if (strSize != "")
            {
                StrQuery += " And appSizeId In(" + strSize + ")";
            }
            else
            {
                StrQuery += " And tblProductDetail.appIsDefault=1";
            }
            StrQuery += " and tblProduct.appIsActive=1";

            StrQuery += " ) as tblBestSeller";
            StrQuery += " Where RowNumber BETWEEN (" + strPageIndex + " -1) * " + strPageSize + " + 1 AND(((" + strPageIndex + " -1) * " + strPageSize + "+ 1) + " + strPageSize + ") - 1";
            StrQuery += "  order by appDisplayOrder ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;

        }

        public string GetCountProductByPaging(string strProperty, string strColor, string strSize, string strOrderBy, string strMinPrice, string strMaxPrice, string strRate)
        {
            string StrQuery = " Select ROW_NUMBER() OVER( ORDER BY ";
            if (strOrderBy != "")
            {
                StrQuery += strOrderBy;
            }
            StrQuery += " )AS RowNumber,CASE WHEN tblDeal.appDiscountPer IS NULL THEN tblProductDetail.appPrice ELSE CAST((isnull(tblProductDetail.appPrice, 0) - ((isnull(tblProductDetail.appPrice, 0) * tblDeal.appDiscountPer) / 100)) AS Decimal(10, 2)) END AS AppPrice,tblProductColor.appProductColorID,tblProductDetail.AppSizeID, tblProductDetail.AppMRP,tblBestSeller.appBestSellerID,tblBestSeller.appProductID,tblBestSeller.appIsActive,tblBestSeller.appDisplayOrder,tblProduct.appProductName,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblProductImage.appSmallImage,tblProductImage.appNormalImage,tblProductImage.appLargeImage,tblProduct.appIsFeatured,tblProduct.appIsNewArrival,tblProduct.appIsBestSeller,tblProductDetail.appProductDetailID ,case when tblDeal.appDiscountPer is null then Cast(ROUND((100-(isnull(dbo.tblProductDetail.appPrice,0)*100)/isnull(dbo.tblProductDetail.appMRP,0)),0) as Decimal(2)) else Cast(ROUND((100-(isnull( cast((isnull(tblProductDetail.appPrice,0)-((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100)) as Decimal(10,2)),0)*100)/isnull(dbo.tblProductDetail.appMRP,0)),0) as decimal(2,0))  end appOff  ";
            StrQuery += "    from tblBestSeller inner join tblProduct on tblProduct.appProductID=tblBestSeller.appProductID and tblBestSeller.appIsActive=1 ";
            StrQuery += "     inner join tblProductColor on tblProductColor.appProductID=tblProduct.appProductID  ";
            if (strColor == "")
            {
                StrQuery += "  and tblProductColor.appIsDefault=1 ";
            }
            StrQuery += "    inner join tblColor on tblColor.appColorID=tblProductColor.appColorID ";
            StrQuery += "   inner join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID and tblProductImage.appIsDefault=1  ";
            StrQuery += "    inner join tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID and tblProductDetail.appIsDefault=1 ";
            StrQuery += " Left Join tblDeal on tblDeal.appProductID=tblProduct.appProductID ";
            if (strProperty != "")
            {
                StrQuery += " INNER JOIN (Select appProductID From tblProductProperty Where tblProductProperty.appPropertyPreValueID in (" + strProperty + ") group by appProductID) tblProductProperty On tblProductProperty.appProductId=tblBestSeller.appProductId";
            }
            StrQuery += " Where 1=1 ";

            if (strColor != "")
            {
                StrQuery += " And tblProductColor.appColorId In(" + strColor + ")";
            }
            else
            {
                StrQuery += " And tblProductColor.appIsDefault=1";
            }
            if (strMinPrice != "" && strMaxPrice != "")
            {
                StrQuery += " and ((CASE WHEN tblDeal.appDiscountPer IS NULL THEN tblProductDetail.appPrice ELSE CAST((isnull(tblProductDetail.appPrice, 0) - ((isnull(tblProductDetail.appPrice, 0) * tblDeal.appDiscountPer) / 100)) AS Decimal(10, 2)) END)*" + strRate + ") between " + strMinPrice + " and " + strMaxPrice + "";
            }
            if (strSize != "")
            {
                StrQuery += " And appSizeId In(" + strSize + ")";
            }
            else
            {
                StrQuery += " And tblProductDetail.appIsDefault=1";
            }
            StrQuery += " and tblProduct.appIsActive=1";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table.Rows.Count.ToString();

        }
    }
}
