
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
	public class tblCurrency : _tblCurrency
	{
		public tblCurrency()
		{
		
		}
        public DataTable LoadGridData(string strColumnName, string strColumnValue)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = " select * from tblCurrency where 1=1 ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += " and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            else if (strColumnName == "0" && string.IsNullOrEmpty(strColumnValue))
            {
                StrQuery += " and ( appCurrency LIKE '%" + strColumnValue + "%'";
                StrQuery += " or  AppRate LIKE '%" + strColumnValue + "%' )";
            }

            StrQuery += " order by appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }


        public void SetDefaultColor(string strCurrencyId = "0")
        {
            string StrQuery = " UPDATE tblCurrency SET appIsDefault='False' ";
            base.LoadFromRawSql(StrQuery);
            if (strCurrencyId != "0")
            {
                StrQuery = "UPDATE tblCurrency SET appIsDefault='True',appIsActive='True' Where AppCurrencyID=" + strCurrencyId;
                base.LoadFromRawSql(StrQuery);
            }
        }
	}
}
