
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
	public class tblCustomer : _tblCustomer
	{
		public tblCustomer()
		{
		
		}
        public DataTable LoadGridData(string strColumnName, string strColumnValue)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = "select appCustomerID, appFirstName,appLastName,appEmailID,appPassword,appMobile,appPhone,appGender,appIsVerified,appImage,appIsActive,appIsNewsLetter,appAddress,appCreatedDate from tblCustomer ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += "where " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            StrQuery += " order by appCustomerID desc";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        //public DataTable LoadCustomer()
        //{

        //    string StrQuery = "select appCustomerID, appFirstName,appLastName,appEmailID,appPassword,appMobile,appPhone,appGender,appIsVerified,appImage,appIsActive,appIsNewsLetter,appAddress,appCreatedDate from tblCustomer Where appIsActive=1 order  ";

        //    base.LoadFromRawSql(StrQuery);
        //    return base.DefaultView.Table;
        //}
	}
}
