
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
    public class tblColor : _tblColor
    {
        public tblColor()
        {

        }
        public DataTable LoadGridData(string strColumnName, string strColumnValue)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = " select * from tblColor where 1=1 ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += " and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            else if (strColumnName == "0" && string.IsNullOrEmpty(strColumnValue))
            {
                StrQuery += " and ( appColorName LIKE '%" + strColumnValue + "%'";
                StrQuery += " or  appColorCode LIKE '%" + strColumnValue + "%' )";
            }

            StrQuery += " order by appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }


        public void SetDefaultColor(string strColorId = "0")
        {
            string StrQuery = " UPDATE tblColor SET appIsDefault='False' ";
            base.LoadFromRawSql(StrQuery);
            if (strColorId != "0")
            {
                StrQuery = "UPDATE tblColor SET appIsDefault='True',appIsActive='True' Where appColorID=" + strColorId;
                base.LoadFromRawSql(StrQuery);
            }
        }
        public DataTable LoadAllColor()
        {
            string StrQuery = " select * from tblColor where appIsActive=1 ";
            StrQuery += " order by appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
