
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
    public class tblExclusive : _tblExclusive
    {
        public tblExclusive()
        {

        }
        public DataTable LoadGridData(string strColumnName, string strColumnValue, string strCategoryID)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = "select tblExclusive.appExclusiveID,tblExclusive.appTitle, tblExclusive.appCategoryID, tblExclusive.appImage,tblExclusive.appLink,tblExclusive.appIsActive,tblExclusive.appDisplayOrder,tblCategory.appCategory from tblExclusive ";
            StrQuery += " inner join tblCategory on tblExclusive.appCategoryID = tblCategory.appCategoryID where 1=1 ";
            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += "and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            if (strCategoryID != "0")
            {
                StrQuery += " and tblExclusive.appCategoryID = " + strCategoryID;
            }
            if (strCategoryID != "0")
            {
                StrQuery += " order by tblExclusive.appDisplayOrder ";
            }
            else
            {
                StrQuery += " order by tblExclusive.appExclusiveID desc";
            }
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadTop2Data(string strCategoryID)
        {

            string StrQuery = "select top 2 tblExclusive.appExclusiveID,tblExclusive.appTitle, tblExclusive.appLink,tblExclusive.appImage  from tblExclusive where appIsActive=1 ";

            if (strCategoryID != "0")
            {
                StrQuery += " and tblExclusive.appCategoryID = " + strCategoryID;
            }
            StrQuery += " order by tblExclusive.appDisplayOrder ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
