
// Generated by MyGeneration Version # (1.3.0.3)

using System;

using System.Data;
namespace BusinessLayer
{
	public class tblFavouriteProduct : _tblFavouriteProduct
	{
		public tblFavouriteProduct()
		{
		
		}
        public DataTable LoadFavouriteProduct(string strCustomerID)
        {
            string StrQuery = "  Select tblFavouriteProduct.appFavouriteProductID,convert(varchar,tblFavouriteProduct.appCreatedDate,103)appCreatedDate,tblProduct.appProductID,tblProduct.appProductName,tblProduct.appProductCode, tblProductDetail.appPrice as appTotalPrice,tblProductColor.appProductColorID,tblProductImage.*,tblProductDetail.appProductDetailID,tblProductDetail.appSellerPrice,	tblProductDetail.appMRP,tblProductDetail.appPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,	tblsize.appSizeID,tblsize.appSize	";
            StrQuery += " From tblFavouriteProduct ";
            StrQuery += " Inner join tblProduct On tblProduct.appProductId=tblFavouriteProduct.appProductId 		";
            StrQuery += " Inner join tblProductColor On tblProduct.appProductId=tblproductColor.appProductId 	";
            StrQuery += " inner join tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID 	";
            StrQuery += " Inner Join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID 	";
            StrQuery += " Inner join tblSize on tblsize.appSizeId=tblProductDetail.appsizeId	";
            StrQuery += " Where tblProductDetail.appIsDefault=1 and tblProductImage.appIsActive=1 and tblProductImage.appIsDefault=1  and tblProductColor.appIsDefault=1  and tblFavouriteProduct.appCustomerID=" + strCustomerID;
            StrQuery += " order by tblFavouriteProduct.appFavouriteProductID Desc";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
	}
}
