
// Generated by MyGeneration Version # (1.3.0.3)
using System;
using System.Data;

namespace BusinessLayer
{
    public class tblManifest : _tblManifest
    {
        public tblManifest()
        {

        }
        public DataTable LoadGridData(string strStartDate, string strEndDate)
        {
            string StrQuery = "select appManifestID,appUploadedManifest,Convert(varchar,appCreatedDate,105)appCreatedDate, case when appUploadedManifest is null then 'true' else 'flase' end as appIsShow from tblManifest where 1=1 ";
            if (strStartDate != "" & strEndDate != "")
            {
                StrQuery += "and appCreatedDate between convert(datetime,'" + strStartDate + "',103) and convert(datetime,'" + strEndDate + "',103) ";
            }
            StrQuery += " order by appManifestID Desc  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
