
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
    public class tblPixcelCode : _tblPixcelCode
    {
        public tblPixcelCode()
        {

        }
        public DataTable LoadPixelCode(string strProductID)
        {
            //  strColumnValue = strColumnValue.Replace("'", "");
            string StrQuery = "select  tblPixcelCode.appPixcelCodeID,tblPixcelCode.appName,tblPixcelCode.appComment,tblPixcelCode.appProductId,tblPixcelCode.appIsActive,convert(varchar,tblPixcelCode.appCreatedDate,103)appCreatedDate,tblProduct.appProductName ";
            StrQuery += " from tblPixcelCode ";
            StrQuery += " inner join tblProduct on tblProduct.appProductId=tblPixcelCode.appProductId ";

            if (strProductID != "" && strProductID != "0")
            {
                StrQuery += " and  tblPixcelCode.appProductId=" + strProductID;
            }

            StrQuery += " order by tblPixcelCode.appCreatedDate desc  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable GetPixcelCode(string strProductID)
        {
            //  strColumnValue = strColumnValue.Replace("'", "");
            string StrQuery = "select  tblPixcelCode.appPixcelCodeID,tblPixcelCode.appName,tblPixcelCode.appComment,tblPixcelCode.appProductId,tblPixcelCode.appIsActive,convert(varchar,tblPixcelCode.appCreatedDate,103)appCreatedDate ";
            StrQuery += " from tblPixcelCode where 1=1 and tblPixcelCode.appIsActive=1 ";
            if (strProductID != "" && strProductID != "0")
            {
                StrQuery += " and  tblPixcelCode.appProductId=" + strProductID;
            }
            StrQuery += " order by tblPixcelCode.appCreatedDate desc  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
