
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Collections;
using System.Collections.Specialized;

namespace BusinessLayer
{
    public class tblPinCode : _tblPinCode
    {
        public tblPinCode()
        {

        }
        public DataTable LoadGridData( String strPinCode = "",string strCountry = "", string strState = "", string strCity = "")
        {
            //  strColumnValue = strColumnValue.Replace("'", "");
            string StrQuery = "select tblPincode.*,tblCountry.appCountry, tblState.appState, tblCity.appCity  from tblPincode ";
            StrQuery += " Inner join tblCity on tblCity.appCityID=tblPincode.appCityID ";
            StrQuery += " Inner join tblState ON tblState.appStateID = tblCity.appStateID  ";
            StrQuery += " INNER JOIN tblCountry ON tblCountry.appCountryID = tblState.appCountryID where 1=1 ";
            if (strPinCode != "" )
            {
                StrQuery += " and  tblPincode.appPinCode LIKE '%" + strPinCode + "%' ";
            }
            if (strCountry != "" && strCountry != "0")
            {
                StrQuery += " and  tblCountry.appCountryID="  + strCountry ;
            }
            if (strState != "" && strState != "0")
            {
                StrQuery += " and  tblState.appStateID=+"  + strState ;
            }
            if (strCity != "" && strCity != "0")
            {
                StrQuery += " and  tblCity.appCityID=" + strCity ;
            }
            
            //StrQuery += " order by tblSubCategory.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        //public void InsertCountriesXMLData(string strPINCODE, string strControlingStation, string strLocationCode, string strDefaultCity, string strCITYNAME, string strSTATE_UNIONTERRITORY, string strZone, string strRegion, string strEXP, string strToPay, string strCOD)
        //{
        //    ListDictionary parameters = new ListDictionary();
        //    parameters.Add("@PINCODE",strPINCODE);
        //    parameters.Add("@ControlingStation", strControlingStation);
        //    parameters.Add("@LocationCode", strLocationCode);
        //    parameters.Add("@DefaultCity", strDefaultCity);
        //    parameters.Add("@CITYNAME", strDefaultCity);
        //    parameters.Add("@STATE_UNIONTERRITORY", strSTATE_UNIONTERRITORY);
        //    parameters.Add("@Zone", strZone);
        //    parameters.Add("@Region", strRegion);
        //    parameters.Add("@EXP", strEXP);
        //    parameters.Add("@ToPay", strToPay);
        //    parameters.Add("@COD", strCOD);
        //    base.LoadFromSql("UploadBulkData_Pincode", parameters);
            
        //}
        public string  InsertCountriesXMLData(string strXML)
        {
            string flag = "";
            ListDictionary parameters = new ListDictionary();
            parameters.Add("@XmlDocument", strXML);
            base.LoadFromSql("UploadBulkData_Pincode", parameters);
            DataTable dt =  base.DefaultView.Table;
            if (dt.Rows.Count > 0)
            {
                return dt.Rows[0][0].ToString();
            }
            else
            {
                return "Found Some problem";
            }
        }

    }
}
