
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
    public class tblProductImage : _tblProductImage
    {
        public tblProductImage()
        {

        }
        public DataTable LoadGridData(string strProductColorID)
        {

            string StrQuery = " select appProductImageID,appThumbImage,appNormalImage,appLargeImage,appSmallImage,appDisplayOrder,appIsActive,appIsDefault,appProductColorID ";
            StrQuery += " from tblProductImage";
            StrQuery += " Where 1=1 ";

            if (strProductColorID != "0")
            {
                StrQuery += " and  tblProductImage.appProductColorID=" + strProductColorID;
            }
            StrQuery += " order by tblProductImage.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public void SetProductDefaultImage(string strProductColorID, string strProductImageID = "0")
        {
            string StrQuery = " UPDATE tblProductImage SET appIsDefault='False' Where appProductColorID=" + strProductColorID;
            base.LoadFromRawSql(StrQuery);
            if (strProductImageID != "0")
            {
                StrQuery = "UPDATE tblProductImage SET appIsDefault='True',appIsActive='True' Where appProductColorID=" + strProductColorID + " And appProductImageID=" + strProductImageID;
                base.LoadFromRawSql(StrQuery);
            }
        }

        public DataTable LoadProductColorImg(string strProductID, string strProductColorID = "0", string strColorId = "")
        {
            string StrQuery = "  Select tblDeal.appDiscountPer,tblProductColor.appProductColorID,tblProductImage.*,tblProductDetail.appProductDetailID,tblProductDetail.appSellerPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,tblColor.appColorName,tblColor.appColorCode,case when tblDeal.appDiscountPer Is null then tblProductDetail.appPrice else (isnull(tblProductDetail.appPrice,0)-((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100)) End appPrice,case when tblDeal.appDiscountPer Is null then tblProductDetail.appMRP else tblProductDetail.appPrice End appMRP,case when tblDeal.appDiscountPer Is null then 0 else tblProductDetail.appMRP End appMRP1,tblDeal.appTitle	From tblProductColor 	inner join tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID and tblProductDetail.appIsDefault=1		Inner Join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID 	Inner Join tblColor On tblColor.appColorId=tblProductColor.appColorID		Left Join tblDeal on tblDeal.appProductID=tblProductColor.appProductID and tblDeal.appIsActive=1	Where  tblProductImage.appIsActive=1  ";
            if (strProductID != "")
            {
                StrQuery += " and  tblProductColor.appProductID=" + strProductID;
            }
            if (strProductColorID != "0")
            {
                StrQuery += " and  tblProductImage.appProductColorID=" + strProductColorID;
            }
            if (strColorId != "" && strColorId != "0")
            {
                StrQuery += " and  tblColor.appColorID=" + strColorId;
            }
            if ((strColorId == "" || strColorId == "0") && strProductColorID == "0")
            {
                StrQuery += " and tblProductColor.appIsDefault=1";
            }
            StrQuery += " order by tblProductImage.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadProductInformation(string strProductID, string strProductColorID = "0", string strProductDetailID = "0", int iQty = 1, decimal  decCouponDiscount = 0)
        {
            string StrQuery = " Select  tblProduct.appProductID,tblProduct.appProductCode,tblProduct.appProductName," + iQty + " as appQty,case when tblDeal.appDiscountPer Is null then Cast(Round((" + iQty + "*(tblProductDetail.appPrice-" + decCouponDiscount + ")),0) as int) else Cast(Round((" + iQty + "*(isnull(tblProductDetail.appPrice,0)-((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100))) ,0) as int)End as appTotalPrice,tblProductColor.appProductColorID,tblProductImage.*,tblProductDetail.appProductDetailID,Cast(Round(tblProductDetail.appSellerPrice,0) as int)as appSellerPrice,Cast(Round(tblProductDetail.appMRP,0) as int) as appMRP ,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,tblsize.appSizeID,tblsize.appSize,Cast(Round((tblProductDetail.appPrice*" + iQty + "),0) as int) as appPrice ,Cast(Round(tblProductDetail.appPrice,0) as int) as appRealPrice,case when tblDeal.appDiscountPer Is null then Cast(Round(" + (iQty * decCouponDiscount) + ",0) as int) else Cast(Round((" + iQty + "*((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100)),0) as int) End appDiscountPrice,case when tblDeal.appDiscountPer Is null then Cast(Round(" + decCouponDiscount + ",0) as int) else Cast(Round(((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100) ,0) as int) End appRealDiscountPrice ";
            StrQuery += " From tblProductColor  Inner join tblProduct On tblProduct.appProductId=tblproductColor.appProductId inner join tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID 	Inner Join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID Inner join tblSize on tblsize.appSizeId=tblProductDetail.appsizeId		Left Join tblDeal on tblDeal.appProductID=tblProductColor.appProductID and tblDeal.appIsActive=1 Where  tblProductImage.appIsActive=1 and tblProductImage.appIsDefault=1 ";
            if (strProductID != "")
            {
                StrQuery += " and  tblProductColor.appProductID=" + strProductID;
            }
            if (strProductColorID != "0")
            {
                StrQuery += " and  tblProductImage.appProductColorID=" + strProductColorID;
            }
            else
            {
                StrQuery += " and tblProductColor.appIsDefault=1 ";
            }
            if (strProductDetailID != "0")
            {
                StrQuery += " and   tblProductDetail.appProductDetailID=" + strProductDetailID;
            }
            StrQuery += " order by tblProductImage.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
