
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
    public class tblPropertyPreValue : _tblPropertyPreValue
    {
        public tblPropertyPreValue()
        {

        }
        public DataTable LoadGridData(string strColumnName, string strColumnValue, string strPropertyId)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = " select * From tblPropertyPreValue where 1=1 ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += " and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            if (strPropertyId != "0")
            {
                StrQuery += " and  tblPropertyPreValue.appPropertyID=" + strPropertyId;
            }
            StrQuery += " order by tblPropertyPreValue.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadPropertyValue(string strPropertyId)
        {
            string StrQuery = " select * From tblPropertyPreValue where appIsActive=1 ";
            StrQuery += " and  tblPropertyPreValue.appPropertyID=" + strPropertyId;
            StrQuery += " order by tblPropertyPreValue.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
       
        public DataTable LoadSearchPropertyValue(string strPropertyId, string strCategory, string strSubCategory)
        {
            string StrQuery = "Select tblPropertyPreValue.appPropertyPreValueID,tblPropertyPreValue.appPreValue,tblPropertyPreValue.appPropertyID from tblPropertyPreValue	inner join (Select distinct(appPropertyPreValueID)	From tblProductProperty	inner join (Select distinct(vw_SerachProduct.appproductid) From vw_SerachProduct  ";
            StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Inner Join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID ";
            StrQuery += " Where 1=1";
            if (strCategory != "")
            {
                StrQuery += " And appCategory='" + strCategory + "'";
            }
            if (strSubCategory != "")
            {
                StrQuery += " And appSubCategory='" + strSubCategory + "'";
            }
            StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=vw_SerachProduct.appProductID ";
            StrQuery += " )tblproduct on tblproduct.appproductid=tblProductProperty.appproductid	) tblProductProperty on tblProductProperty.appPropertyPreValueID=tblPropertyPreValue.appPropertyPreValueID ";
            StrQuery += " where tblPropertyPreValue.appIsActive=1  and  tblPropertyPreValue.appPropertyID=" + strPropertyId;
            StrQuery += " order by tblPropertyPreValue.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadProductPropertyValue(string strPropertyId, string strProduct)
        {
            string StrQuery = "Select tblPropertyPreValue.appPropertyPreValueID,tblPropertyPreValue.appPreValue,tblPropertyPreValue.appPropertyID from tblPropertyPreValue	inner join (Select distinct(appPropertyPreValueID)	From tblProductProperty	inner join (Select distinct(vw_SerachProduct.appproductid) From vw_SerachProduct  ";
            if (strProduct != "")
            {
                StrQuery += " Where  (vw_SerachProduct.appProductName Like  '%" + strProduct + "%' or vw_SerachProduct.appSKUNo Like  '" + strProduct + "') ";
            }
            StrQuery += " )tblproduct on tblproduct.appproductid=tblProductProperty.appproductid	) tblProductProperty on tblProductProperty.appPropertyPreValueID=tblPropertyPreValue.appPropertyPreValueID ";
            StrQuery += " where tblPropertyPreValue.appIsActive=1  and  tblPropertyPreValue.appPropertyID=" + strPropertyId;
            StrQuery += " order by tblPropertyPreValue.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadOtherCategoryWisePropertyValue(string strPropertyId, string strTableName)
        {
            string StrQuery = "Select tblPropertyPreValue.appPropertyPreValueID,tblPropertyPreValue.appPreValue,tblPropertyPreValue.appPropertyID from tblPropertyPreValue	inner join (Select distinct(appPropertyPreValueID)	From tblProductProperty	inner join (Select distinct(" + strTableName + ".appproductid) From  " + strTableName ;
            StrQuery += " Where " + strTableName + ".appIsActive=1 )tblproduct on tblproduct.appproductid=tblProductProperty.appproductid	) tblProductProperty on tblProductProperty.appPropertyPreValueID=tblPropertyPreValue.appPropertyPreValueID ";
            StrQuery += " where tblPropertyPreValue.appIsActive=1  and  tblPropertyPreValue.appPropertyID=" + strPropertyId;
            StrQuery += " order by tblPropertyPreValue.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
