
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
    public class tblProductDetail : _tblProductDetail
    {
        public tblProductDetail()
        {

        }
        public DataTable LoadGridData(string strProductId, string strProductColorId)
        {
            string StrQuery = " Select tblProductDetail.appProductDetailID,tblProductDetail.appProductColorID,tblProductDetail.appIsDefault,tblProductDetail.appSellerPrice,tblProductDetail.appMRP,tblProductDetail.appPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,tblProductDetail.appSizeID,tblProductColor.appColorID,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblSize.appsize";
            StrQuery += " From tblProductDetail";
            StrQuery += " Inner join tblProductColor On tblProductColor.appProductColorID=tblProductDetail.appProductColorID";
            StrQuery += " inner join tblColor On tblColor.appColorID=tblProductColor.appColorID";
            StrQuery += " 	Left Join tblsize on tblSize.appsizeId=tblProductDetail.appsizeId";
            StrQuery += " Where 1=1 ";

            if (strProductId != "0")
            {
                StrQuery += " and  tblProductColor.appProductID=" + strProductId;
            }
            if (strProductColorId != "0")
            {
                StrQuery += " and  tblProductColor.appProductColorID=" + strProductColorId;
            }
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public void SetProductDetailDefault(string ProductColorID, string strProductDetailID = "0")
        {
            string StrQuery = " UPDATE tblProductDetail SET appIsDefault='False' Where appProductColorID=" + ProductColorID;
            base.LoadFromRawSql(StrQuery);
            if (strProductDetailID != "0")
            {
                StrQuery = "UPDATE tblProductDetail SET appIsDefault='True' Where appProductDetailID=" + strProductDetailID + " And appProductColorID=" + ProductColorID;
                base.LoadFromRawSql(StrQuery);
            }
        }

        public DataTable LoadProductColorWiseSize(string strProductColorId)
        {
            string StrQuery = " Select tblProductDetail.*,tblsize.appSize ";
            StrQuery += " From tblProductDetail";
            StrQuery += " Inner Join tblSize on tblsize.appSizeId=tblProductDetail.appSizeId";
            StrQuery += " Where appProductColorID=" + strProductColorId;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadProductIDs(string strProductDetailId)
        {
            string StrQuery = " select tblProductDetail.appProductColorID,tblProductDetail.appProductDetailID,tblProductDetail.appQuantity,tblProductColor.appProductID from tblProductDetail ";
            StrQuery += " inner join tblProductColor on tblProductDetail.appProductColorID = tblProductColor.appProductColorID ";
            StrQuery += "where tblProductDetail.appProductDetailID = " + strProductDetailId;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable GetProductDetail(string strProductDetailId)
        {
            string StrQuery = " Select tblDeal.appDiscountPer,tblProductColor.appProductColorID,tblProductDetail.appProductDetailID,tblProductDetail.appSellerPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,case when tblDeal.appDiscountPer Is null then tblProductDetail.appPrice else (isnull(tblProductDetail.appPrice,0)-((isnull(tblProductDetail.appPrice,0)*tblDeal.appDiscountPer)/100)) End appPrice,case when tblDeal.appDiscountPer Is null then tblProductDetail.appMRP else tblProductDetail.appPrice End appMRP,case when tblDeal.appDiscountPer Is null then 0 else tblProductDetail.appMRP End appMRP1,tblDeal.appTitle	From   tblProductDetail	inner join tblProductColor on tblProductColor.appProductColorID=tblProductDetail.appProductColorID 		Left Join tblDeal on tblDeal.appProductID=tblProductColor.appProductID and tblDeal.appIsActive=1	";
            StrQuery += "where tblProductDetail.appProductDetailID = " + strProductDetailId;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable GetProductWiseProductDetail(string strProductId)
        {
            string StrQuery = "Select tblProductDetail.appProductDetailID,tblProductDetail.appSKUNo,tblProductDetail.appQuantity,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblSize.appSize	From tblProductDetail inner join tblProductColor on tblProductColor.appProductColorID=tblProductDetail.appProductColorID inner join tblColor on tblColor.appColorID=tblProductColor.appColorID inner join tblSize on tblSize.appSizeID=tblProductDetail.appSizeID ";
            StrQuery += "where tblProductColor.appProductID= " + strProductId;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable GetReportQtyWise(string strQty)
        {
            string StrQuery = " Select tblProduct.appProductName,tblProduct.appProductCode,tblProductDetail.appProductDetailID,tblProductDetail.appSKUNo,tblProductDetail.appQuantity,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblSize.appSize	,tblProductImage.appSmallImage,tblProductImage.appNormalImage From tblProductDetail  inner join tblProductColor on tblProductColor.appProductColorID=tblProductDetail.appProductColorID inner join tblProduct on tblProduct.appProductID=tblProductColor.appProductID left join tblColor on tblColor.appColorID=tblProductColor.appColorID left join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID  and tblProductImage.appIsDefault=1 left join tblSize on tblSize.appSizeID=tblProductDetail.appSizeID ";
            StrQuery += "where tblProductDetail.appQuantity <= " + strQty;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable GetReportSKUNOWise(string strSKUNO)
        {
            string StrQuery = " Select tblProduct.appProductName,tblProduct.appProductCode,tblProductDetail.appProductDetailID,tblProductDetail.appSKUNo,tblProductDetail.appQuantity,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblSize.appSize	,tblProductImage.appSmallImage,tblProductImage.appNormalImage From tblProductDetail  inner join tblProductColor on tblProductColor.appProductColorID=tblProductDetail.appProductColorID inner join tblProduct on tblProduct.appProductID=tblProductColor.appProductID left join tblColor on tblColor.appColorID=tblProductColor.appColorID left join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID  and tblProductImage.appIsDefault=1 left join tblSize on tblSize.appSizeID=tblProductDetail.appSizeID ";
            if (strSKUNO!="")
            {
                StrQuery += "where tblProductDetail.appSKUNo Like '%" + strSKUNO + "%'";
            }
            StrQuery += " order by tblProduct.appProductID Desc  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
