
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
	public class tblPropertySubCategory : _tblPropertySubCategory
	{
		public tblPropertySubCategory()
		{
		
		}
        public DataTable LoadGridData(string strPropertyId, string strCategoryId, string strSubCategoryId)
        {

            string StrQuery = " select tblPropertySubCategory.appPropertySubCategoryID,tblPropertySubCategory.appDisplayOrder,tblPropertySubCategory.appIsActive,tblSubCategory.appSubCategory,tblCategory.appCategory from tblPropertySubCategory ";
            StrQuery += " Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblPropertySubCategory.appSubCategoryID ";
            StrQuery += " Inner Join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID ";
            StrQuery += "  where 1=1 ";

            if (!string.IsNullOrEmpty(strCategoryId) & strCategoryId != "0")
            {
                StrQuery += " and tblCategory.appCategoryID=" + strCategoryId;
            }
            if (!string.IsNullOrEmpty(strSubCategoryId) & strSubCategoryId != "0")
            {
                StrQuery += " and tblSubCategory.appSubCategoryID=" + strSubCategoryId;
            }

            StrQuery += " and tblPropertySubCategory.appPropertyID=" + strPropertyId;
            StrQuery += " order by tblPropertySubCategory.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadUnSelectedCategories(string strPropertyID, string strCategoryId)
        {

            string StrQuery = "   select * From tblSubCategory    ";
            StrQuery += " where  appCategoryID=" + strCategoryId + " and     ";
            StrQuery += " tblSubCategory.appSubCategoryID  Not In ( select appSubCategoryID From tblPropertySubCategory Where appPropertyID=" + strPropertyID + ")   ";


            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    
	}
}
