
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
    public class tblProduct : _tblProduct
    {
        public tblProduct()
        {

        }
        public DataTable LoadGridData(string strColumnName, string strColumnValue, string strCategory, string strSubCategory, string strColor)
        {
            strColumnValue = strColumnValue.Replace("'", "");
            string StrQuery = " Select tblProduct.appProductID,tblProduct.appIsActive,tblProduct.appProductName,tblProduct.appProductCode,tblProduct.appProductTag,tblProduct.appDescription,tblProduct.appMetaKeyWord,tblProduct.appMetaDescription,tblProduct.appBrowserTitle,tblProduct.appIsColor,tblProduct.appIsSize	,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage	,tblProductImage.appThumbImage,tblProductImage.appNormalImage,tblProductImage.appLargeImage,tblProductImage.appSmallImage";
            StrQuery += " From tblProduct  ";
            StrQuery += " Left join tblProductColor On tblProductColor.appProductID=tblProduct.appProductID ";
            if (!(strColor != "" && strColor != "0"))
           
            {
                StrQuery += " And  tblProductColor.appIsDefault=1  ";
            }
            StrQuery += " Left join tblColor on tblColor.appColorID=tblProductColor.appColorID ";
            StrQuery += " Left join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID and tblProductImage.appIsDefault=1   ";
            if ((strCategory != "" || strSubCategory != "") && (strCategory != "0" || strSubCategory != "0"))
            {
                StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Where 1=1 ";
                if (strCategory != "" && strCategory != "0")
                {
                    StrQuery += " And tblSubCategory.appCategoryID=" + strCategory;
                }
                if (strSubCategory != "" && strSubCategory != "0")
                {
                    StrQuery += " And tblSubCategory.appSubCategoryID=" + strSubCategory;
                }
                StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=tblProduct.appProductID ";
            }

            StrQuery += " where  1=1 ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += " and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            else if (strColumnName == "0" && strColumnValue != "")
            {
                StrQuery += " and ( appProductName LIKE '%" + strColumnValue + "%'";
                StrQuery += " or  appProductCode LIKE '%" + strColumnValue + "%' )";
            }

            if (strColor != "" && strColor != "0")
            {
                StrQuery += " And tblProductColor.appColorId =" + strColor;
            }
    
            StrQuery += " order by tblProduct.appProductID Desc  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadAllProduct(string strCategory, string strSubCategory, string strProperty, string strColor, string strSize, string strOrderBy)
        {
            string StrQuery = "Select vw_SerachProduct.* From vw_SerachProduct ";
            StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Inner Join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID where 1=1";
            if (strCategory != "")
            {
                StrQuery += " And appCategory='" + strCategory + "'";
            }
            if (strSubCategory != "")
            {
                StrQuery += " And appSubCategory='" + strSubCategory + "'";
            }
            StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=vw_SerachProduct.appProductID ";

            if (strProperty != "")
            {
                StrQuery += " INNER JOIN (Select * From tblProductProperty Where tblProductProperty.appPropertyPreValueID in (" + strProperty + ")	) tblProductProperty On tblProductProperty.appProductId=vw_SerachProduct.appProductId";
            }
            StrQuery += " Where 1=1 and tblProduct.appIsActive=1 ";

            if (strColor != "")
            {
                StrQuery += " And appColorId In(" + strColor + ")";
            }
            else
            {
                StrQuery += " And appProductColorIsDefault=1";
            }
            if (strSize != "")
            {
                StrQuery += " And appSizeId In(" + strSize + ")";
            }
            else
            {
                StrQuery += " And appProductDetailIsDefault=1";
            }
            if (strOrderBy != "")
            {
                StrQuery += " Order by " + strOrderBy;
            }
            else
            {
                StrQuery += " Order by vw_SerachProduct.appProductID Desc";
            }

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadAllProductNameWise(string strProductName, string strProperty, string strColor, string strSize, string strOrderBy)
        {
            string StrQuery = "Select vw_SerachProduct.* From vw_SerachProduct ";
            //StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Inner Join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID ";
            //if (strCategory != "")
            //{
            //    StrQuery += " And appCategory='" + strCategory + "'";
            //}
            //if (strSubCategory != "")
            //{
            //    StrQuery += " And appSubCategory='" + strSubCategory + "'";
            //}
            //StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=vw_SerachProduct.appProductID ";

            if (strProperty != "")
            {
                StrQuery += " INNER JOIN (Select * From tblProductProperty Where tblProductProperty.appPropertyPreValueID in (" + strProperty + ")	) tblProductProperty On tblProductProperty.appProductId=vw_SerachProduct.appProductId";
            }
            StrQuery += " Where 1=1 ";
            if (strProductName != "")
            {
                StrQuery += " And vw_SerachProduct.appProductName Like '%" + strProductName + "%'";
            }
            if (strColor != "")
            {
                StrQuery += " And appColorId In(" + strColor + ")";
            }
            else
            {
                StrQuery += " And appProductColorIsDefault=1";
            }
            if (strSize != "")
            {
                StrQuery += " And appSizeId In(" + strSize + ")";
            }
            else
            {
                StrQuery += " And appProductDetailIsDefault=1";
            }
            if (strOrderBy != "")
            {
                StrQuery += " Order by " + strOrderBy;
            }
            else
            {
                StrQuery += " Order by vw_SerachProduct.appProductID Desc";
            }

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadHomeProduct(string strFieldName, string strTopRecord = "")
        {
            string StrQuery = "Select ";
            if (strTopRecord != "")
            {
                StrQuery += " Top " + strTopRecord;
            }
            StrQuery += "   appProductName,appProductCode,case when appDescription is null then '' else case When LEN(appDescription) <= 40  then appDescription else LEFT(appDescription, 40) + '...' End End appDescription,appProductTag,appIsNewArrival,appIsFeatured,appIsBestSeller,tblProductDetail.appSellerPrice,tblProductDetail.appMRP,tblProductDetail.appPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblProductImage.appThumbImage,tblProductImage.appNormalImage,tblProductImage.appLargeImage,tblProductImage.appSmallImage 	From tblProduct inner join ( Select * From tblProductColor where tblProductColor.appIsDefault=1)  tblProductColor on tblProductColor.appProductID=tblProduct.appProductID inner join ( Select * From tblProductDetail where tblProductDetail.appIsDefault=1)tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID inner join tblColor on tblColor.appColorID=tblProductColor.appColorID		inner join (Select * From tblProductImage Where tblProductImage.appIsDefault=1) tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID  Where " + strFieldName + "=1 Order by tblProduct.appProductID Desc";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadProductInfo(string strProductId)
        {

            string StrQuery = "Select tblProduct.appProductID,appProductName,appProductCode,case when appDescription is null then '' else case When LEN(appDescription) <= 40  then appDescription else LEFT(appDescription, 40) + '...' End End appDescription,appProductTag,appIsNewArrival,appIsFeatured,appIsBestSeller,tblProductColor.appProductColorID,tblProductDetail.appProductDetailID,tblProductDetail.appSellerPrice,tblProductDetail.appMRP,tblProductDetail.appPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,tblProductDetail.appSizeId,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblProductImage.appThumbImage,tblProductImage.appNormalImage,tblProductImage.appLargeImage,tblProductImage.appSmallImage 	From tblProduct inner join ( Select * From tblProductColor where tblProductColor.appIsDefault=1)  tblProductColor on tblProductColor.appProductID=tblProduct.appProductID  inner join ( Select * From tblProductDetail where tblProductDetail.appIsDefault=1)tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID inner join tblColor on tblColor.appColorID=tblProductColor.appColorID	inner join (Select * From tblProductImage Where tblProductImage.appIsDefault=1) tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID  ";
            StrQuery += " Where tblProduct.appProductID=" + strProductId;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public Boolean IsProductInOrder(string StrProductId)
        {
            string StrQuery = " Select tblSubOrder.appSubOrderID,tblSubOrder.appSubOrderNo,tblSubOrder.appQty,tblSubOrder.appSellingPrice,tblSubOrder.appSubOrderStatusID,convert(varchar, tblSubOrder.appMaxDispatchDate,103)appMaxDispatchDate,tblProductDetail.appProductDetailID,tblProduct.appProductName,tblProduct.appProductCode,tblProductDetail.appProductColorID,tblProductDetail.appIsDefault,tblProductDetail.appSellerPrice,tblProductDetail.appMRP,tblProductDetail.appPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,tblProductDetail.appSizeID,tblProductColor.appColorID,tblColor.appColorName,tblColor.appColorCode,tblColor.appColorImage,tblSize.appsize,tblProductImage.appNormalImage";
            StrQuery += " From tblSubOrder  ";
            StrQuery += " Inner join tblProductDetail on tblProductDetail.appProductDetailID=tblSubOrder.appProductDetailID  ";
            StrQuery += " Inner join tblProductColor On tblProductColor.appProductColorID=tblProductDetail.appProductColorID ";
            StrQuery += " Inner join tblProduct on tblProduct.appProductID=tblProductColor.appProductID  ";
            StrQuery += " Inner join tblProductImage On tblProductImage.appProductColorID=tblProductColor.appProductColorID   ";
            StrQuery += " inner join tblColor On tblColor.appColorID=tblProductColor.appColorID  ";
            StrQuery += " Left Join tblsize on tblSize.appsizeId=tblProductDetail.appsizeId  ";
            StrQuery += " where  tblProduct.appProductID=" + StrProductId;

            base.LoadFromRawSql(StrQuery);
            if (base.DefaultView.Table.Rows.Count > 0)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        public DataTable LoadAllProductPagingWise(string strPageSize, string strPageIndex, string strCategory, string strSubCategory, string strProperty, string strColor, string strSize, string strOrderBy, string strProduct, string strMinPrice, string strMaxPrice, string strRate)
        {
            string StrQuery = "Select * From ( Select ROW_NUMBER() OVER( ORDER BY ";
            if (strOrderBy != "")
            {
                StrQuery += strOrderBy;
            }
            else
            {
                StrQuery += " vw_SerachProduct.appProductID Desc";
            }

            StrQuery += " )AS RowNumber,vw_SerachProduct.* From vw_SerachProduct ";

            StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Inner Join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID ";


            StrQuery += " Where 1=1";

            if (strCategory != "")
            {
                StrQuery += " And appCategory='" + strCategory + "'";
            }
            if (strSubCategory != "")
            {
                StrQuery += " And appSubCategory='" + strSubCategory + "'";
            }
            StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=vw_SerachProduct.appProductID ";

            if (strProperty != "")
            {
                StrQuery += " INNER JOIN (Select appProductId From tblProductProperty Where tblProductProperty.appPropertyPreValueID in (" + strProperty + ") group by appProductId		) tblProductProperty On tblProductProperty.appProductId=vw_SerachProduct.appProductId";
            }
            StrQuery += " Where 1=1 ";

            if (strColor != "")
            {
                StrQuery += " And appColorId In(" + strColor + ")";
            }
            else
            {
                StrQuery += " And appProductColorIsDefault=1";
            }
            if (strSize != "")
            {
                StrQuery += " And appSizeId In(" + strSize + ")";
            }
            else
            {
                StrQuery += " And appProductDetailIsDefault=1";
            }
            if (strMinPrice != "" && strMaxPrice != "")
            {
                StrQuery += " and (AppPrice*" + strRate + ") between " + strMinPrice + " and " + strMaxPrice + "";
            }
            if (strProduct != "")
            {
                StrQuery += " And (appProductName Like  '%" + strProduct + "%' or appSKUNo Like  '" + strProduct + "') ";
            }
            //if (strOrderBy != "")
            //{
            //    StrQuery += " Order by " + strOrderBy;
            //}
            //else
            //{
            //    StrQuery += " Order by appProductID Desc";
            //}
            StrQuery += " ) as tblProduct";

            StrQuery += " Where RowNumber BETWEEN (" + strPageIndex + " -1) * " + strPageSize + " + 1 AND(((" + strPageIndex + " -1) * " + strPageSize + "+ 1) + " + strPageSize + ") - 1";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadAllProductSearchPagingWise(string strPageSize, string strPageIndex, string strProductName, string strProperty, string strColor, string strSize, string strOrderBy, string strMinPrice, string strMaxPrice, string strRate)
        {
            string StrQuery = "Select * From ( Select ROW_NUMBER() OVER( ORDER BY ";
            if (strOrderBy != "")
            {
                StrQuery += strOrderBy;
            }
            else
            {
                StrQuery += " vw_SerachProduct.appProductID Desc";
            }

            StrQuery += " )AS RowNumber, vw_SerachProduct.* From vw_SerachProduct ";

            if (strProperty != "")
            {
                StrQuery += " INNER JOIN (Select * From tblProductProperty Where tblProductProperty.appPropertyPreValueID in (" + strProperty + ")	) tblProductProperty On tblProductProperty.appProductId=vw_SerachProduct.appProductId";
            }
            StrQuery += " Where 1=1";
            if (strProductName != "")
            {
                StrQuery += " And vw_SerachProduct.appProductName Like '%" + strProductName + "%'";
            }
            if (strColor != "")
            {
                StrQuery += " And appColorId In(" + strColor + ")";
            }
            else
            {
                StrQuery += " And appProductColorIsDefault=1";
            }
            if (strMinPrice != "" && strMaxPrice != "")
            {
                StrQuery += " and (AppPrice*" + strRate + ") between " + strMinPrice + " and " + strMaxPrice + "";
            }

            if (strSize != "")
            {
                StrQuery += " And appSizeId In(" + strSize + ")";
            }
            else
            {
                StrQuery += " And appProductDetailIsDefault=1";
            }
            StrQuery += " ) as tblProduct";

            StrQuery += " Where RowNumber BETWEEN (" + strPageIndex + " -1) * " + strPageSize + " + 1 AND(((" + strPageIndex + " -1) * " + strPageSize + "+ 1) + " + strPageSize + ") - 1";
            //if (strOrderBy != "")
            //{
            //    StrQuery += " Order by " + strOrderBy;
            //}
            //else
            //{
            //    StrQuery += " Order by appProductID Desc";
            //}

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public string LoadAllProductCount(string strCategory, string strSubCategory, string strProperty, string strColor, string strSize, string strOrderBy, string strMinPrice, string strMaxPrice, string strRate, string strProduct = "")
        {
            string StrQuery = "Select * From ( Select ROW_NUMBER() OVER( ORDER BY ";
            if (strOrderBy != "")
            {
                StrQuery += strOrderBy;
            }
            else
            {
                StrQuery += " vw_SerachProduct.appProductID Desc";
            }

            StrQuery += " )AS RowNumber,vw_SerachProduct.* From vw_SerachProduct ";
            StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory  ";
            StrQuery += " Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	 ";
            StrQuery += " Inner Join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID  ";

            StrQuery += "  where 1=1 ";
            if (strCategory != "")
            {
                StrQuery += " And appCategory='" + strCategory + "'";
            }
            if (strSubCategory != "")
            {
                StrQuery += " And appSubCategory='" + strSubCategory + "'";
            }
            StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=vw_SerachProduct.appProductID ";

            if (strProperty != "")
            {
                StrQuery += " INNER JOIN (Select distinct(tblProductProperty.appProductID) From tblProductProperty Where tblProductProperty.appPropertyPreValueID in (" + strProperty + ")	) tblProductProperty On tblProductProperty.appProductId=vw_SerachProduct.appProductId";
            }
            StrQuery += " Where 1=1 ";

            if (strColor != "")
            {
                StrQuery += " And appColorId In(" + strColor + ")";
            }
            else
            {
                StrQuery += " And appProductColorIsDefault=1";
            }
            if (strMinPrice != "" && strMaxPrice != "")
            {
                StrQuery += " and (AppPrice*" + strRate + ") between " + strMinPrice + " and " + strMaxPrice + "";
            }
            if (strSize != "")
            {
                StrQuery += " And appSizeId In(" + strSize + ")";
            }
            else
            {
                StrQuery += " And appProductDetailIsDefault=1";
            }
            if (strProduct != "")
            {
                StrQuery += " And (appProductName Like  '%" + strProduct + "%' or appSKUNo Like  '" + strProduct + "') ";
            }
            //if (strOrderBy != "")
            //{
            //    StrQuery += " Order by " + strOrderBy;
            //}
            //else
            //{
            //    StrQuery += " Order by appProductID Desc";
            //}

            StrQuery += " ) as tblProduct";

           
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table.Rows.Count.ToString();
        }

        public string LoadAllProductSearchCount(string strProductName, string strProperty, string strColor, string strSize, string strOrderBy, string strMinPrice, string strMaxPrice, string strRate)
        {
            string StrQuery = "Select * From ( Select ROW_NUMBER() OVER( ORDER BY ";
            if (strOrderBy != "")
            {
                StrQuery += strOrderBy;
            }
            else
            {
                StrQuery += " vw_SerachProduct.appProductID Desc";
            }

            StrQuery += " )AS RowNumber, vw_SerachProduct.* From vw_SerachProduct ";

            if (strProperty != "")
            {
                StrQuery += " INNER JOIN (Select * From tblProductProperty Where tblProductProperty.appPropertyPreValueID in (" + strProperty + ")	) tblProductProperty On tblProductProperty.appProductId=vw_SerachProduct.appProductId";
            }
            StrQuery += " Where 1=1 ";
            if (strProductName != "")
            {
                StrQuery += " And vw_SerachProduct.appProductName Like '%" + strProductName + "%'";
            }
            if (strColor != "")
            {
                StrQuery += " And appColorId In(" + strColor + ")";
            }
            else
            {
                StrQuery += " And appProductColorIsDefault=1";
            }
            if (strMinPrice != "" && strMaxPrice != "")
            {
                StrQuery += " and (AppPrice*" + strRate + ") between " + strMinPrice + " and " + strMaxPrice + "";
            }
            if (strSize != "")
            {
                StrQuery += " And appSizeId In(" + strSize + ")";
            }
            else
            {
                StrQuery += " And appProductDetailIsDefault=1";
            }
            StrQuery += " ) as tblProduct";

            //if (strOrderBy != "")
            //{
            //    StrQuery += " Order by " + strOrderBy;
            //}
            //else
            //{
            //    StrQuery += " Order by appProductID Desc";
            //}

            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table.Rows.Count.ToString();
        }

        public DataTable LoadProductImageByProductID(string strProductID)
        {
            string StrQuery = "";
            StrQuery += "select tblproduct.appProductID,tblProductImage.appSmallImage from tblproduct ";
            StrQuery += "inner join tblProductColor on tblProductColor.appProductID = tblproduct.appProductID ";
            StrQuery += "inner join tblProductImage on tblProductImage.appProductColorID = tblProductColor.appProductColorID ";
            StrQuery += "where tblProductColor.appIsDefault = 1 and tblProductImage.appIsDefault = 1 and tblProduct.appIsActive=1 ";
            StrQuery += "and tblproduct.appProductID=" + strProductID;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;

        }

        public DataTable LoadRecentProduct(string strRecentProductDetailIds, string strCurentProductDetailId)
        {

            string StrQuery = " Select tblProductDetail.appProductDetailID,tblProductDetail.appProductColorID,tblProductImage.appNormalImage,tblProductImage.appThumbImage,tblColor.appColorID,tblColor.appColorName,	 tblColor.appColorCode,tblColor.appColorImage,tblProduct.appProductID,tblProduct.appProductName,case When tblProduct.appIsColor=1  Then tblColor.appColorName else '' End appColorLink ";
            StrQuery += " From tblProductDetail  ";
            StrQuery += " inner join tblProductColor on tblProductColor.appProductColorID=tblProductDetail.appProductColorID ";
            StrQuery += " inner join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID and tblProductImage.appIsDefault=1   ";
            StrQuery += " inner join  tblColor on tblColor.appColorID=tblProductColor.appColorID ";
            StrQuery += " inner join tblProduct on tblProduct.appProductID=tblProductColor.appProductID";
            StrQuery += " where  tblProduct.appIsActive=1 ";
            StrQuery += " and  tblProductDetail.appProductDetailID in (" + strRecentProductDetailIds + ") and tblProductDetail.appProductDetailID<>" + strCurentProductDetailId;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable ExportAllInfoProduct(string strColumnName, string strColumnValue, string strCategory, string strSubCategory, string strColor, string strProductId)
        {
            strColumnValue = strColumnValue.Replace("'", "");
            string StrQuery = "  Select tblProduct.appProductName,tblProduct.appProductCode,tblProduct.appDescription,case when tblProduct.appIsNewArrival=1 then 'True' else 'False' End appIsNewArrival,Case When tblProduct.appIsBestSeller=1 then 'True' else 'False' End appIsBestSeller,case when tblProduct.appIsFeatured=1 then 'True' else 'False' End appIsFeatured ,tblProduct.appMetaKeyWord,tblProduct.appMetaDescription,case when tblProduct.appIsColor=1 then 'True' else 'False' end appIsColor,Case When tblProduct.appIsSize=1 then 'True' Else 'False' end appIsSize,tblProduct.appEstimatedDeliveryDays,tblProductDetail.appSellerPrice,tblProductDetail.appMRP,tblProductDetail.appPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo ,isnull(tblSize.appSize,'-')appSize,isnull(tblColor.appColorName,'-')appColorName,isnull(tblColor.appColorCode,'-')appColorCode	";
            StrQuery += " From tblProduct  ";
            StrQuery += " Left Join tblProductColor on tblProductColor.appProductID=tblProduct.appProductID";
            StrQuery += " Left Join tblColor on tblColor.appColorID=tblProductColor.appColorID";
            StrQuery += " Left Join tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID";
            StrQuery += " Left Join tblSize on tblSize.appSizeId=tblProductDetail.appSizeId";
            if ((strCategory != "" || strSubCategory != "") && (strCategory != "0" || strSubCategory != "0"))
            {
                StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Where 1=1 ";
                if (strCategory != "" && strCategory != "0")
                {
                    StrQuery += " And tblSubCategory.appCategoryID=" + strCategory;
                }
                if (strSubCategory != "" && strSubCategory != "0")
                {
                    StrQuery += " And tblSubCategory.appSubCategoryID=" + strSubCategory;
                }
                StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=tblProduct.appProductID ";
            }

            StrQuery += " where  1=1 ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += " and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            else if (strColumnName == "0" && strColumnValue != "")
            {
                StrQuery += " and ( appProductName LIKE '%" + strColumnValue + "%'";
                StrQuery += " or  appProductCode LIKE '%" + strColumnValue + "%' )";
            }
            if (strColor != "" && strColor != "0")
            {
                StrQuery += " And tblProductColor.appColorId =" + strColor;
            }
            if (strProductId != "")
            {
                StrQuery += " And tblProduct.appProductID in (" + strProductId + ")";
            }
            StrQuery += " order by tblProduct.appProductID Desc  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public decimal GetCategoryWiseMaxPrice(string strCategory, string strSubCategory)
        {
            string StrQuery = " Select Max(vw_SerachProduct.appPrice) From vw_SerachProduct ";
            StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Inner Join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID ";
            StrQuery += " Where 1=1";
            if (strCategory != "")
            {
                StrQuery += " And appCategory='" + strCategory + "'";
            }
            if (strSubCategory != "")
            {
                StrQuery += " And appSubCategory='" + strSubCategory + "'";
            }
            StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=vw_SerachProduct.appProductID ";
            base.LoadFromRawSql(StrQuery);
            if (base.DefaultView.Table.Rows.Count > 0)
            {
                if (base.DefaultView.Table.Rows[0][0].ToString() != "")
                {
                    return Convert.ToDecimal(base.DefaultView.Table.Rows[0][0].ToString());
                }
                else
                {
                    return 10000;
                }
            }
            else
            {
                return 10000;
            }
        }

        public decimal GetProductNameWiseMaxPrice(string strProduct)
        {
            string StrQuery = " Select Max(vw_SerachProduct.appPrice) From vw_SerachProduct ";
            if (strProduct != "")
            {
                StrQuery += " Where  (vw_SerachProduct.appProductName Like  '%" + strProduct + "%' or vw_SerachProduct.appSKUNo Like  '" + strProduct + "') ";
            }
            base.LoadFromRawSql(StrQuery);
            if (base.DefaultView.Table.Rows.Count > 0)
            {
                if (base.DefaultView.Table.Rows[0][0].ToString() != "")
                {
                    return Convert.ToDecimal(base.DefaultView.Table.Rows[0][0].ToString());
                }
                else
                {
                    return 10000;
                }
            }
            else
            {
                return 10000;
            }
        }

        public decimal GetOtherCategoryWiseMaxPrice(string strTableName)
        {
            string StrQuery = " Select Max(vw_SerachProduct.appPrice) From vw_SerachProduct ";
            StrQuery += " inner join (Select distinct(" + strTableName + ".appproductid) From  " + strTableName + "  Where " + strTableName + ".appIsActive=1 ) tblTemp on tblTemp.appProductId=vw_SerachProduct.appProductId";
            base.LoadFromRawSql(StrQuery);
            if (base.DefaultView.Table.Rows.Count > 0)
            {
                if (base.DefaultView.Table.Rows[0][0].ToString() != "")
                {
                    return Convert.ToDecimal(base.DefaultView.Table.Rows[0][0].ToString());
                }
                else
                {
                    return 10000;
                }
            }
            else
            {
                return 10000;
            }
        }
    }
}
