
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;

namespace BusinessLayer
{
    public class tblRelatedProduct : _tblRelatedProduct
    {
        public tblRelatedProduct()
        {

        }
        public DataTable LoadUnSelectedProduct(string strProductId, string strCategoryId, string strSubCategoryId)
        {

            string StrQuery = "Select vw_SerachProduct.* From vw_SerachProduct ";
            StrQuery += " Inner Join (Select distinct(tblProductSubCategory.appProductID) From tblProductSubCategory 	Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Where 1=1 ";
            if (strCategoryId != "" && strCategoryId != "0")
            {
                StrQuery += " And tblSubCategory.appCategoryID=" + strCategoryId;
            }
            if (strSubCategoryId != "" && strSubCategoryId != "0")
            {
                StrQuery += " And tblSubCategory.appSubCategoryID=" + strSubCategoryId;
            }
            StrQuery += " )tblProductSubCategory On tblProductSubCategory.appProductID=vw_SerachProduct.appProductID ";

            StrQuery += " Where 1=1 ";

            StrQuery += " And appProductColorIsDefault=1";

            StrQuery += " And appProductDetailIsDefault=1";
            StrQuery += " and vw_SerachProduct.appProductID<>" + strProductId + " and vw_SerachProduct.appProductId Not In( select distinct(appRelatedID ) From tblRelatedProduct Where appProductID=" + strProductId + " )";
            StrQuery += " Order by vw_SerachProduct.appProductID Desc";


            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadSelectedProduct(string strProductId)
        {

            string StrQuery = " Select appRelatedProductID,tblRelatedProduct.appProductID,tblRelatedProduct.appRelatedID,tblRelatedProduct.appIsActive,tblRelatedProduct.appDisplayOrder ,tblProduct.appProductName,tblProductImage.appThumbImage,tblProductImage.appNormalImage,tblProductImage.appLargeImage,tblProductImage.appSmallImage 	From tblRelatedProduct";
            StrQuery += " Inner Join tblProduct On tblProduct.appProductId=tblRelatedProduct.appRelatedID ";
            StrQuery += " Left join tblProductColor On tblProductColor.appProductID=tblProduct.appProductID and tblProductColor.appIsDefault=1  ";
            StrQuery += " Left join tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID and tblProductImage.appIsDefault=1   ";

            StrQuery += "  where 1=1 ";
            StrQuery += " and tblRelatedProduct.appProductID=" + strProductId;
            StrQuery += " Order by tblRelatedProduct.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadRelatedProduct(string strProductId)
        {

            string StrQuery = " Select tblRelatedProduct.appRelatedProductID,tblRelatedProduct.appIsActive,tblRelatedProduct.appDisplayOrder,tblProduct.appProductID,appProductName,appProductCode,case when appDescription is null then '' else case When LEN(appDescription) <= 40  then appDescription else LEFT(appDescription, 40) + '...' End End appDescription,appProductTag,appIsNewArrival,appIsFeatured,appIsBestSeller,tblProductDetail.appSellerPrice,tblProductDetail.appMRP,tblProductDetail.appPrice,tblProductDetail.appQuantity,tblProductDetail.appSKUNo,tblColor.appColorName,tblColor.appColorCode,tblProductImage.appThumbImage,tblProductImage.appNormalImage,tblProductImage.appLargeImage,tblProductImage.appSmallImage 	From tblRelatedProduct inner join  tblProduct On tblProduct.appProductID=tblRelatedProduct.appRelatedID inner join ( Select * From tblProductColor where tblProductColor.appIsDefault=1)  tblProductColor on tblProductColor.appProductID=tblProduct.appProductID  inner join ( Select * From tblProductDetail where tblProductDetail.appIsDefault=1)tblProductDetail on tblProductDetail.appProductColorID=tblProductColor.appProductColorID inner join tblColor on tblColor.appColorID=tblProductColor.appColorID		inner join (Select * From tblProductImage Where tblProductImage.appIsDefault=1) tblProductImage on tblProductImage.appProductColorID=tblProductColor.appProductColorID Where tblRelatedProduct.appIsActive=1 ";
            StrQuery += " and tblRelatedProduct.appProductID=" + strProductId;
            StrQuery += " Order by tblRelatedProduct.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

   

    }
}
