
// Generated by MyGeneration Version # (1.3.0.3)

using System;

namespace BusinessLayer
{
	public class tblReturnOrderDetail : _tblReturnOrderDetail
	{
		public tblReturnOrderDetail()
		{
		
		}
	}
}
