
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
	public class tblReviews : _tblReviews
	{
		public tblReviews()
		{
		
		}
        public DataTable LoadPendingReviewGridData(string strProductDetailID = "", string strSellerID = "", int intreviewStatus = 0, string strStartDate = "", string strEndDate = "")
        {
            string StrQuery = "select  tblProduct.appProductID,tblProduct.appProductName,  tblCustomer.appFirstName + ' ' + tblCustomer.appLastName as appFullname,tblCustomer.appFirstName,tblReviews.*,tblProductImage.*,tblProduct.*,tblProductDetail.*,tblProductColor.*,tblColor.*, tblsize.* from tblReviews ";
            StrQuery += "  Inner join tblCustomer on tblCustomer.appCustomerID=tblReviews.appCustomerID   ";
            StrQuery += "   inner join tblProductDetail on tblProductDetail.appProductDetailID=tblReviews.appProductDetailID   ";
            StrQuery += "   Inner join tblProductColor On tblProductColor.appProductColorID=tblProductDetail.appProductColorID  ";
            StrQuery += "   inner join tblColor On tblColor.appColorID=tblProductColor.appColorID  ";
            StrQuery += "   Left Join tblsize on tblSize.appsizeId=tblProductDetail.appsizeId  ";
            StrQuery += "      inner join tblProduct On tblProductColor.appProductID=tblProduct.appProductID  ";
            StrQuery += "    INNER JOIN tblProductImage ON tblProductColor.appProductColorID = tblProductImage.appProductColorID  ";
            StrQuery += "       where 1=1 and tblProductImage.appIsDefault=1  ";
            StrQuery += " and tblReviews.appReviewStatus Not in (" + Convert.ToInt32(Enums.Enum_ReviewStatus.Submitted).ToString() + ") ";
            if (intreviewStatus != 0)
            {
                StrQuery += " And tblReviews.appReviewStatus =" + intreviewStatus;
            }
            if (strProductDetailID != "0" && strProductDetailID != "")
            {
                StrQuery += " And tblProductDetail.appProductDetailID=" + strProductDetailID;
            }
            if (strStartDate != "0" && strStartDate != "" && strEndDate != "0" && strEndDate != "")
            {
                StrQuery += " and  convert(varchar , tblReviews.appReviewDate,103) between convert(varchar , '" + strStartDate + "',103) and convert(varchar , '" + strEndDate + "',103) ";
            }
            StrQuery += " order by appReviewDate desc";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadPendingCommentsDataAdmin(string strColumnName, string strColumnValue, string strProductDetailID = "", int intreviewStatus = 0, string strStartDate = "", string strEndDate = "")
        {

            strColumnValue = strColumnValue.Replace("'", "");
            string StrQuery = "    select  tblProduct.appProductID,  tblProduct.appProductName, tblReviews.*,tblCustomer.appFirstName,tblCustomer.appLastName , ";
            StrQuery += "   tblReviews.appRating  ";
            StrQuery += "   from tblReviews    ";
            StrQuery += "     Inner join tblCustomer on tblCustomer.appCustomerID=tblReviews.appCustomerID     ";
        
            StrQuery += "     inner join tblProductDetail on tblProductDetail.appProductDetailID=tblReviews.appProductDetailID  ";
            StrQuery += "  Inner join tblProductColor On tblProductColor.appProductColorID=tblProductDetail.appProductColorID     ";
            StrQuery += "  inner join tblProduct On tblProductColor.appProductID=tblProduct.appProductID     ";

            StrQuery += " where tblReviews.appReviewStatus in (" + Convert.ToInt32(Enums.Enum_ReviewStatus.Submitted).ToString() + ") ";
            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {

                StrQuery += " and tblProduct." + strColumnName + " LIKE '%" + strColumnValue + "%'";

            }
            StrQuery += " order by tblReviews.appReviewID Desc ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;

        }
        public DataTable LoadPendingReviewGridDataAdmin(string strColumnName, string strColumnValue, string strProductDetailID = "",  int intreviewStatus = 0, string strStartDate = "", string strEndDate = "")
        {

            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = "select tblProduct.appProductID, tblProduct.appProductName,d.NoOfComments,tblProductImage.appThumbImage ,d.appProductDetailID   ";
            StrQuery += "  from tblProductDetail pd    ";
            StrQuery += "  inner join ( SELECT t2.appProductDetailID,count(*) as NoOfComments   ";
            StrQuery += "  FROM tblReviews t1   ";
            StrQuery += "  INNER JOIN tblProductDetail t2 ON t2.appProductDetailID = t1.appProductDetailID   ";
            StrQuery += "  INNER JOIN tblCustomer t3 ON t3.appCustomerID = t1.appCustomerID  where 1=1  ";
           
            if (intreviewStatus != 0)
            {

                StrQuery += " And t1.appReviewStatus =" + intreviewStatus;

            }
            StrQuery += "  GROUP BY t2.appProductDetailID) d on pd.appProductDetailID = d.appProductDetailID    ";

            StrQuery += "  Inner join tblProductColor On tblProductColor.appProductColorID=pd.appProductColorID     ";
            StrQuery += "  inner join tblColor On tblColor.appColorID=tblProductColor.appColorID      ";
            StrQuery += "  inner join tblProduct On tblProductColor.appProductID=tblProduct.appProductID     ";
            StrQuery += "  INNER JOIN tblProductImage ON tblProductColor.appProductColorID = tblProductImage.appProductColorID        ";
          
            StrQuery += "  where 1=1 and tblProductImage.appIsDefault=1  ";


            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {

                StrQuery += " and tblProduct." + strColumnName + " LIKE '%" + strColumnValue + "%'";

            }


            if (strProductDetailID != "0" && strProductDetailID != "")
            {
                StrQuery += " And tblProductDetail.appProductDetailID=" + strProductDetailID;
            }

            if (strStartDate != "0" && strStartDate != "" && strEndDate != "0" && strEndDate != "")
            {
                StrQuery += " and  convert(varchar , tblReviews.appReviewDate,103) between convert(varchar , '" + strStartDate + "',103) and convert(varchar , '" + strEndDate + "',103) ";
            }
          
          
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;

        }
        public DataTable LoadReviewByID(string strReviewID)
        {
            string StrQuery = "    select Convert (varchar,tblReviews.appReviewDate,106) appReviewDate,tblReviews.appComment,tblCustomer.appFirstName,tblCustomer.appLastName , ";
            StrQuery += " tblReviews.appRating ";
            StrQuery += " from tblReviews   ";
            StrQuery += " Inner join tblCustomer on tblCustomer.appCustomerID=tblReviews.appCustomerID     ";
          
            StrQuery += " inner join tblProductDetail on tblProductDetail.appProductDetailID=tblReviews.appProductDetailID  ";
          
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadReviewsProductvise(string strProductID)
        {
            string StrQuery = "select Convert (varchar,tblReviews.appReviewDate,106) appReviewDate, tblReviews.appProductDetailID, tblCustomer.appFirstName + ' ' + tblCustomer.appLastName as appFullname,tblReviews.appReviewID,tblReviews.appComment  ,tblReviews.appRating,tblReviews.appTitle  ";
            StrQuery += " from tblReviews  ";
            StrQuery += " inner join tblCustomer on tblReviews.appCustomerID=tblCustomer.appCustomerID where 1=1";
            if (strProductID != "0" && strProductID != "")
            {
                StrQuery += " And tblReviews.appProductDetailID ='" + strProductID + "' ";
            }
            StrQuery += "  and tblReviews.appReviewStatus='" + Convert.ToInt32(Enums.Enum_ReviewStatus.Approved).ToString() + "' ";
            StrQuery += " order by tblReviews.appReviewID Desc ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

	}
}
