
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;


namespace BusinessLayer
{
    public class tblSubCategory : _tblSubCategory
    {
        public tblSubCategory()
        {

        }
        public DataTable LoadGridData(string strColumnName, string strColumnValue, string strCategoryId)
        {
            strColumnValue = strColumnValue.Replace("'", "");

            string StrQuery = " select tblSubCategory.appSubCategoryID,tblSubCategory.appSubCategory,tblSubCategory.appIsActive,tblSubCategory.appDisplayOrder,tblSubCategory.appCategoryID,tblCategory.appCategory from tblSubCategory Inner join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID where 1=1 ";

            if (!string.IsNullOrEmpty(strColumnValue) & strColumnName != "0")
            {
                StrQuery += " and " + strColumnName + " LIKE '%" + strColumnValue + "%'";
            }
            if (strCategoryId != "0")
            {
                StrQuery += " and  tblSubCategory.appCategoryID=" + strCategoryId;
            }
            StrQuery += " order by tblSubCategory.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable LoadAllSubCategory()
        {

            string StrQuery = " select * from tblSubCategory where tblSubCategory.appIsActive=1 ";

            StrQuery += " order by tblSubCategory.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable GetAllCategoryProductWise(string strProductId)
        {

            string StrQuery = " Select  distinct(tblCategory.appCategoryID),tblCategory.appCategory	From tblProductSubCategory	Inner Join tblSubCategory on tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Inner Join tblCategory on tblCategory.appCategoryID=tblSubCategory.appCategoryID ";
            StrQuery += " Where tblProductSubCategory.appProductID=" + strProductId;
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }

        public DataTable GetAllSubCategoryProductWise(string strProductId, string strCategory)
        {

            string StrQuery = " Select tblProductSubCategory.appProductSubCategoryID,tblProductSubCategory.appSubCategoryID,tblProductSubCategory.appIsActive	,tblSubCategory.appSubCategory	,tblCategory.appCategoryID,tblCategory.appCategory	From tblProductSubCategory	Inner Join tblSubCategory on tblSubCategory.appSubCategoryID=tblProductSubCategory.appSubCategoryID	Inner Join tblCategory on tblCategory.appCategoryID=tblSubCategory.appCategoryID ";
            StrQuery += "Where tblProductSubCategory.appProductID=" + strProductId + " and tblCategory.appCategoryID=" + strCategory;
            StrQuery += " order by tblProductSubCategory.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    }
}
