
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
namespace BusinessLayer
{
    public class tblSizeSubCategory : _tblSizeSubCategory
    {
        public tblSizeSubCategory()
        {

        }
        public DataTable LoadGridData(string strSizeId, string strCategoryId, string strSubCategoryId)
        {

            string StrQuery = " select tblSizeSubCategory.appSizeSubCategoryID,tblSizeSubCategory.appDisplayOrder,tblSubCategory.appSubCategory,tblCategory.appCategory from tblSizeSubCategory ";
            StrQuery += " Inner Join tblSubCategory On tblSubCategory.appSubCategoryID=tblSizeSubCategory.appSubCategoryID ";
            StrQuery += " Inner Join tblCategory On tblCategory.appCategoryID=tblSubCategory.appCategoryID ";
            StrQuery += "  where 1=1 ";

            if (!string.IsNullOrEmpty(strCategoryId) & strCategoryId != "0")
            {
                StrQuery += " and tblCategory.appCategoryID=" + strCategoryId;
            }
            if (!string.IsNullOrEmpty(strSubCategoryId) & strSubCategoryId != "0")
            {
                StrQuery += " and tblSubCategory.appSubCategoryID=" + strSubCategoryId;
            }

            StrQuery += " and tblSizeSubCategory.appSizeID=" + strSizeId;
            StrQuery += " order by tblSizeSubCategory.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadSizeGridData(string strSubCategoryId)
        {

            string StrQuery = " select tblSizeSubCategory.appSizeSubCategoryID,tblSizeSubCategory.appDisplayOrder,tblSize.appsize from tblSizeSubCategory ";
            StrQuery += " Inner Join tblSize On tblSize.appsizeId=tblSizeSubCategory.appsizeId ";

            StrQuery += "  where 1=1 ";


            StrQuery += " and tblSizeSubCategory.appSubCategoryID=" + strSubCategoryId;
            StrQuery += " order by tblSizeSubCategory.appDisplayOrder  ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadUnselectedSizeGridData(string strSubCategoryId)
        {
            string StrQuery = " select appSize,*  from tblSize where appsizeID NOT IN (select appSizeId from tblSizeSubCategory where appSubCategoryID=" + strSubCategoryId + ")";

           
            StrQuery += "    ";
            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
        public DataTable LoadUnSelectedCategories(string strProductId, string strCategoryId)
        {

            string StrQuery = "   select * From tblSubCategory    ";
            StrQuery += " where  appCategoryID=" + strCategoryId + " and     ";
            StrQuery += " tblSubCategory.appSubCategoryID  Not In (select appSubCategoryID From tblSizeSubCategory Where appSizeID=" + strProductId + ")   ";


            base.LoadFromRawSql(StrQuery);
            return base.DefaultView.Table;
        }
    
    }
}
